var annotated_dup =
[
    [ "ChaseFX", "class_chase_f_x.html", "class_chase_f_x" ],
    [ "CycleFX", "class_cycle_f_x.html", "class_cycle_f_x" ],
    [ "CylonFX", "class_cylon_f_x.html", "class_cylon_f_x" ],
    [ "DimUsingPaletteFX", "class_dim_using_palette_f_x.html", "class_dim_using_palette_f_x" ],
    [ "FFXAFDimmer", "class_f_f_x_a_f_dimmer.html", "class_f_f_x_a_f_dimmer" ],
    [ "FFXAFXFader", "class_f_f_x_a_f_x_fader.html", "class_f_f_x_a_f_x_fader" ],
    [ "FFXAutoFader", "class_f_f_x_auto_fader.html", "class_f_f_x_auto_fader" ],
    [ "FFXBase", "class_f_f_x_base.html", "class_f_f_x_base" ],
    [ "FFXColor", "class_f_f_x_color.html", "class_f_f_x_color" ],
    [ "FFXController", "class_f_f_x_controller.html", "class_f_f_x_controller" ],
    [ "FFXFastLEDPixelController", "class_f_f_x_fast_l_e_d_pixel_controller.html", "class_f_f_x_fast_l_e_d_pixel_controller" ],
    [ "FFXFrameProvider", "class_f_f_x_frame_provider.html", "class_f_f_x_frame_provider" ],
    [ "FFXOverlay", "class_f_f_x_overlay.html", "class_f_f_x_overlay" ],
    [ "FFXPixelController", "class_f_f_x_pixel_controller.html", "class_f_f_x_pixel_controller" ],
    [ "FFXRotate", "class_f_f_x_rotate.html", "class_f_f_x_rotate" ],
    [ "FFXSegment", "class_f_f_x_segment.html", "class_f_f_x_segment" ],
    [ "FFXStateNotifier", "class_f_f_x_state_notifier.html", "class_f_f_x_state_notifier" ],
    [ "FFXStateObserver", "class_f_f_x_state_observer.html", "class_f_f_x_state_observer" ],
    [ "FFXTrigMotion", "class_f_f_x_trig_motion.html", "class_f_f_x_trig_motion" ],
    [ "FlexTimer", "class_flex_timer.html", "class_flex_timer" ],
    [ "JuggleFX", "class_juggle_f_x.html", "class_juggle_f_x" ],
    [ "MotionFX", "class_motion_f_x.html", "class_motion_f_x" ],
    [ "NamedPalettes", "class_named_palettes.html", "class_named_palettes" ],
    [ "PacificaFX", "class_pacifica_f_x.html", "class_pacifica_f_x" ],
    [ "PaletteFX", "class_palette_f_x.html", "class_palette_f_x" ],
    [ "PulseOverlayFX", "class_pulse_overlay_f_x.html", "class_pulse_overlay_f_x" ],
    [ "RainbowFX", "class_rainbow_f_x.html", "class_rainbow_f_x" ],
    [ "SolidFX", "class_solid_f_x.html", "class_solid_f_x" ],
    [ "StepTimer", "class_step_timer.html", "class_step_timer" ],
    [ "TwinkleFX", "class_twinkle_f_x.html", "class_twinkle_f_x" ],
    [ "WaveOverlayFX", "class_wave_overlay_f_x.html", "class_wave_overlay_f_x" ],
    [ "ZipOverlayFX", "class_zip_overlay_f_x.html", "class_zip_overlay_f_x" ]
];